### ISSUE TITLE
Remove useless  'use EDG::WP4::CCM::Element'

### ISSUE THREAD

**Issue by jouvin** [quattor/configuration-modules-core#1168]
Several components have a `use EDG::WP4::CCM::Element` which is useless and now deprecated (causing a deprecation message at component execution). Known components to clean are:

- [ ] ncm-symlink
- [ ] ncm-sysconfig

**Comment by jouvin** [comment]
Missed that it was already done in the master since last release!

**Comment by ned21** [comment]
ncm-sysconfig has functionality (removing files no longer in the profile) that isn't available in metaconfig yet so I'd prefer it not be deprecated.

**Comment by stdweird** [comment]
afaik, ncm-sysconfig is not deprecated at all. we are starting to avoid it because it has no proper schema and no restart option. we should discuss this at the next workshop how to proceed (ncm-metaconfig would require more "run arbitrary commands" hooks; ncm-sysconfig would require at leasta a daemons option (binding a type per service is already possible, but for refined types, we need some TT code or metaconfig magic to eg add quotes, join strings, ...))

**Comment by jouvin** [comment]
In fact I remembered from a previous workshop (see #434) that the intent was to deprecate `ncm-sysconfig`. I don't think I was particularly supporter of this idea and I'm happy if we remove it from the potentially deprecated list and modernize it. With CAF much more featureful now, it may be easier to add the missing features. I updated the description to remove the 'potentially deprecated'.

I still think that this issue can be closed as it has nothing to do with `ncm-sysconfig` usefulness but only with a cleanup required in several components that has in fact already been done!
