### ISSUE TITLE
ncm-cron: Catch cron entries with duplicate names at build time

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#1228]
Currently, multiple entries can be added to the cron entries list with the same name, in this case both entries are written to disk and the most recent (highest numbered) entry in the list wins.

A very long term solution might be to transition from a `list` of cron entries to a `dict` with `name` as the key, a more pragmatic solution would be to validate the names for uniqueness in the schema.

**Comment by ned21** [comment]
I've actually wanted to use this ability to have duplicates in a different way. In some case we couldn't express the schedule we wanted with the timing field alone so we resorted to scheduling the same job multiple times. It would be nice if the multiple schedules with the same name appeared in the same file and used the same log file. (Although this is probably a very niche use case...)

**Comment by jrha** [comment]
That's probably not too hard, but is it a good idea?

**Comment by jrha** [comment]
To add some thoughts as to why the current behaviour is ugly:
* It is confusing to users, who complain that their cron jobs have not been updated, or have "disappeared".
* The overwrite happens on the host at run-time, not compile time, both definitions of the job end up in the profile (and potentially any data-warehouse). The current "last wins" behaviour (i.e. one overwrites the other) would have been preferable if the jobs were a `dict` with name as the key, then at least one would clobber the other at build time.

**Comment by stdweird** [comment]
my 2 cents:
if the order elements in the list is not relevant, list is not the correct type (unless there's no uniqeness, then maybe list is ok).
this is a very friendly patch to address that, switching to a different type (dict-based) would be better, but that would also be a lot more backwards incompatible.

i would support both approaches

**Comment by ned21** [comment]
I don't disagree this can be confusing and contrary to our preferred approach of "fail early, fail explicitly". However we have some experience of trying to retrospectively block implicit overriding. It turns out it's often happening silently and unintentionally but "working". Introducing a duplicate check then "breaks" working code and since this a list there is no easy or efficient way to switch to "just overwrite the old entry and stop complaining": every append() now has to be a "check for an existing entry and overwrite it if it's there" which is slow at compile time, and code development. The result is that users just stop upgrade their components and then we find that a site has implicitly forked from the supported code base because the newer versions broke their code.

**Comment by stdweird** [comment]
@ned21 so we need a function to replace append so people can overwrite the previous value if one exists instead of regular append?
```pan
@{
    Append value (first argument) if it not present yet.
    Presence is verified either by complete value or when 2nd arg is provided, 
    by comparing the value of key (equal to the second argument) (and assuming the values are dict)
}
function append_unique {
    # left as exercise
}
```

**Comment by jrha** [comment]
Or we just allow the check to be disabled?
A `warning()` function would be nice to have in pan...

**Comment by ned21** [comment]
Going the route of deprecation warnings would help because then sites would see if they have any unexpected overrides that can/should be fixed, and report it as a bug if they are using this feature deliberately.

Otherwise I think we should keep the default the same and make sites that want to enforce no-override as an opt-in setting, rather than changing the default.

**Comment by jrha** [comment]
Ok, it's a deprecation warning now.
