### ISSUE TITLE
ncm-metaconfig: missing pan files in build

### ISSUE THREAD

**Issue by wpoely86** [quattor/configuration-modules-core#1487]
When I run `mvn_pack`, and look into the target directory of ncm-metaconfig, the pan templates of:
- kafka
- hnormalise

are not there. No clue why they aren't picked up by maven.

**Comment by jrha** [comment]
I've verified this is still the case and they don't get packaged in RPMs either.

This appears to be because both are missing test unit tests in `src/test/perl/<service>-example.t` (and they are the only ones missing these). See also: https://www.quattor.org/documentation/2015/09/21/textrender-metaconfig.html#add-unittests
