### ISSUE TITLE
preferred component pan structure

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#370]
The current pan code (`config.pan`, `schema.pan` and so forth) is not entirely consistent throught the components.

What is the preferred structure to have
* `config.pan` and `schema.pan` (eg https://github.com/quattor/configuration-modules-core/tree/master/ncm-libvirtd/src/main/pan/components/libvirtd)
* or all of `config.pan`, `schema.pan` `config-rpm.pan` and `config-common.pan`
* and do we still need `config-xml.pan` (most of these have the `code` attribute set)

Other questions: 
* do we need the license in the pan templates
* is panc recent enough to support
 * `prefix` with absolute path
 * `include 'x'` instead of `include {'x'}`

**Comment by jouvin** [comment]
We can do everything! I am not completely sure about what is your question? `schema.pan` by convention is where we put the `bind` statement. So if you want to build the schema from some common parts, I'd suggest to put this part into another template like `schema-common.pan` and include this template in `schema.pan` rather than using `schema.pan` for the common part and put the `bind` statement in `config.pan` for example.
