### ISSUE TITLE
ncm-chkconfig: startstop behaviour

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#379]
it would be interesting that the `startstop` service attribute implied that during each run of `ncm-chkconfig`, the service is started/stopped if it's state is not what it's supposed to be. 
currently, the `startstop` implies a service `start` or `stop` when there's a change from e.g. `off` to `on`. when the service was initially started and then failed e.g. due to misconfiguration or permisison problem, a fix will not lead to running service (i guess nobody is in favour to also add restart attribute to eg `dirperm`).

**Comment by jrha** [comment]
@stdweird behaviour understood?

**Comment by stdweird** [comment]
no :smile: changing the status for next reboot and starting/stopping it are 2 different issues (`ncm-systemd` will always try to start/stop, even if it was flagged for start/stop on next reboot).

**Comment by jrha** [comment]
Lets discuss at the workshop

**Comment by jrha** [comment]
Discussed at March 2017 workshop, decided to document current behaviour and leave it be.

**Comment by ned21** [comment]
The outcome of the discussion was that ```startstop=true``` SHOULD cause the component to actively manage the state of the server and ensure that the running state matches the configured state. However since this is not causing an active problem for anyone, and use of the ncm-chkconfig code will be phased out as people move to EL7 and systemd, there's no benefit to fixing it and it will be left as-is.

If anyone does find this functionality to be problematic then please reopen the ticket.
