### ISSUE TITLE
ncm-spma: NoAction and /etc/yum.d issues

### ISSUE THREAD

**Issue by ned21** [quattor/configuration-modules-core#536]
[sub cleanup_old_repos](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/yum.pm#L77) executes a change to the filesystem even in NoAction mode.

Guarding the [call point](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/yum.pm#L794) with a ```if (!$NoAction)``` seems to break the yum-configure.t unit test (I have not debugged this in depth but it appears that $NoAction is not set when running under unit tests).

sub generate_repos does respect NoAction but this can lead to mis-leading results. --noaction appears to show now change to the installed packages, but when run without --noaction there is an update to /etc/yum.d and package changes are performed. 

A related issue, that may require it's own ticket, is that when userpkgs = yes then /etc/yum.d is not cleared of invalid repositories. While this is a useful configuration, it should really be its own setting, user-repositories.

(Meta: is it time to move the management of /etc/yum.d/* to its own component to allow finer grained control over yum configuration versus installed package sets?)

**Comment by stdweird** [comment]
a. a bit lower, the `initialize_repos_dir` also has an unguarded `mkpath`. I'm wondering if a `CAF::NoAction` module with a set of common guarded methods might help?

b. wrt to the unittest failing, any details? (fix might be similar to https://github.com/quattor/configuration-modules-core/pull/535/files#diff-eea37931bd644c06c5f5922ee7def4bbR40 which i discovered today; if you skip the execution of a method, that index needs to be adjusted too) (but please don't break my PR :smile: )

c. i don't understand the issue when you run without `--noaction`

d. yes, open an issue for this (shouldn't be that hard to implment).

e. and when would this predependency of spma run (in particular, how are we going update it)? (but i'm infavour of at least factoring out the repository code out of `yum.pm` in a `yum/repos.pm`)

**Comment by ned21** [comment]
b) I put ```if (!$NoAction)``` around [line 794](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/yum.pm#L794) then the configure method returns 0, with cleanup_old_repos as the last called sub. I hypothesise that the unit tests do not set $NoAction directly so the sub was executed under unit test, and since the unlink fails, it returns 0.

c) Scenario: You run with noaction, it says "1 package to install". That package is "safe" / known quantity / etc, so you run it without noaction because it's only going to add 1 package and there's no harm in that. /etc/yum.d then gets updated and ncm-spma starts to add/remove hundreds of packages. The SysAdmin now has to endure a painful conversation with their boss....

d) Done. #538

e) I thought it could be listed as a pre-dependency of ncm-spma and I see the potential for problems but it could be made to work?

**Comment by stdweird** [comment]
c. the solution to this is the following imho:
1. set `pluginconfpath` and `reposdir` in the `yum.conf` (instead of assuming the default)
 2. run the yum commands specifying which `yum.conf` to use (instead of assuming the default)
 3. support yum priorities plugin configuration (very easy once is #535 merged)
 4. on NoAction, create a mktemp `/tmp/yum-spma`  (0600 permissions) with the usual `etc/yum*` substructure, and modified/adapted `yum.conf` etc etc (special care for paths in the configfiles, such as the versionlock list etc). (we need to disable the noaction in filewriter instances for this to work).
  5. if you expect this to work for `userpkgs=yes` (and/or new `userrepos=yes`): `reposdir` is a list of directories, we need to figure out which repo config wins; but one could set `reposdir=/tmp/yum-spma/etc/yum.repos.d,/etc/yum.repos.d` (in case the first config wins) and the quattor managed repos will be the new temp ones, everything else is user responsability (well, excpet the repo files that are left incase they aren't configured anymore)
 6. cleanup the temp stuff

i'd say this is doable, writing unittests that test this `--noaction` behaviour is probbaly more work then adapting the code. (i'm happy you set the milestone to `15.10` :smile: )

the other option is to support rollback in CAF::FileWriter, so modify the files when `--noaction` is specified, and rollback when completed (but good luck with handling crashes/exceptions).

**Comment by stdweird** [comment]
@ned21 i moved the milestone since you also moved the milestone of #565
i think i also addressed all issues in that PR (let me know if there are things that i forgot to cover)
