### ISSUE TITLE
ncm-filesystems: using protected_mounts from fstab

### ISSUE THREAD

**Issue by kwaegema** [quattor/configuration-modules-core#574]
Hi, with my PR https://github.com/quattor/configuration-modules-core/pull/562 , I introduced some new protected mounts and fs_types. This now does not seems to match with this line: https://github.com/quattor/configuration-modules-core/blob/master/ncm-filesystems/src/main/perl/filesystems.pm#L28

The bad thing: ncm-filesystems fails on the servers.
ncm-filesystems uses the configuration tree of ncm-fstab, but this is nowhere verified or linked together..
The problem thus did not arise when compiling, but only when running the components, it complains about the nonexistance of protected_mounts  (because we changed it to the new structure in our templates).

An easy solution is to also use the new paths in ncm-filesystems,i.e. 'copying the protected function of fstab to filesystems, like it is merely done already now..But is there a better solution? Mentioning the protected_mounts in the ncm-filesystems schema probably would have shown this earlier, but still needs reimplementing.  Moving this 'protected' stuff to ncm-lib-blockdevices keeps it at one place but I don't know if that is the right place for doing that. This would also mean that that whole part of ncm-fstab tree needs to move I guess..

**Comment by stdweird** [comment]
if the `protected_hash` method from ncm-fstab does the same as the one from ncm-filesystem, let ncm-filesystem be a child of ncm-fstab? (use `use parent qw(NCM::Compoent::fstab);` instead of current `our @ISA = qw (NCM::Component);`.  that garantees consistent behaviour.

for unittesting, move anything that requires `NCM::Component::Fstab` to ncm-fstab and test it in that component. and use a mocked one for the ncm-filesystems tests.

but moving all common code to ncm-lib-blockdevices is also a possible solution.

**Comment by ned21** [comment]
I thought ncm-filesystems was deprecated in favour of ncm-fstab? I remember we switched because ncm-filesystems could wipe out filesystems on a live host which made us scared. I checked our code base and don't see this being used - is anyone still using it?

**Comment by jrha** [comment]
We're apparently using it to create a `tmpfs` filesystem on three hosts.

**Comment by kwaegema** [comment]
@jrha that is something that can be done with fstab :smile: 
We use it for our ceph servers - to have disks recreated after replacement

**Comment by kwaegema** [comment]
we don't use this for ceph anymore
