### ISSUE TITLE
ncm-spma: spma-run 

### ISSUE THREAD

**Issue by stdweird** [quattor/configuration-modules-core#764]
there is an rpmlint error with ncm-spma regarding `spma-run`. it is installed in the /usr/lib/perl/... dir, but now has 644 permissions, so it is not usable as a script.

questions: 
* can we get rid of spma-run?
* is it needed as a script? and if so, should we move elsewhere

**Comment by ned21** [comment]
It's still required. The solution to the same problem we ended up using on Linux is much simpler but I think Solaris 11 has some additional work to make things like boot environments work. For now we should move it to the bin directory to make rpmlint happy, or in fact not ship it on Linux at all.

**Comment by stdweird** [comment]
@ned21 any details on what is required on solaris? because that should be supported via ncm-ncd (and a small wrapper like in the yumng PR is all you should need.

some remarks about spma-run (just had look at it): it's untainted, has requirement on ncm-query (not refected in the rpm), it takes a lock, but unclear if it's the same lock ncm-ncd would take, it also doesn't do anything with `/.spma-run` like the yumng one does
if you want a bootstrap script for solaris, we should create one, and not call it spma-run, but bootstrap or something similar :smile:

**Comment by ned21** [comment]
@msmark - can you remind us what the caveat is with Solaris BEs?

**Comment by msmark** [comment]
Originally I invented `spma-run` for Solaris 11, see #129, with the expectation at the time that it would be useful for future Yum work.  No you can't get rid of it.  On Solaris, `spma-run` can be called by `ncm-spma` to make changes immediately, or if `/software/components/spma/run` is set to `no` (and this is the way we use it) then `ncm-spma` only runs `spma-run --noaction` to determine if any package changes are pending, as you can see [here](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/ips.pm#L604).  An external process (a shutdown script) is responsible for running `spma-run --execute` and `spma-run --get-be-name` when a host is rebooted.

**Comment by stdweird** [comment]
this is seriously strange but i think i understand your point :smile: 
you basically want to run `ncm-ncd --co whatever --spma_with_noaction_if_spma_is_a_dependency`. if you think this is usefaul (specify noaction bit for particular component(s) instead of all components), you should certainly open an issue on ncm-ncd (because that can also be useful for linux, esp if set via config file).
i don't know what BEs are, so not sure that can be moved to ncm-ncd as well.

**Comment by msmark** [comment]
Not quite. On shutdown we do:

`ncm-ncd -configure -all`

This also invokes the `spma` component, which is actually configured via `/software/components/spma/run = no` to make no changes but to create a [command file](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/ips.pm#L584) instead that will instruct a future invocation of `spma-run` on exactly what `pkg install` command-line arguments are required to bring the host up-to-date.  It also tells us if there are any pending package changes required, which it informs us via a [flag file](https://github.com/quattor/configuration-modules-core/blob/master/ncm-spma/src/main/perl/spma/ips.pm#L613).

All configuration changes made by the above `ncm-ncd` command occur in the live OS.

Now we execute `spma-run --execute` which executes the `pkg install` command that the `spma` component generated for us which includes the `--be-name` argument used for creating a new [boot environment](https://docs.oracle.com/cd/E23824_01/html/E21801/) (BE) inside which all package changes are made (i.e. not in the live OS, but will become the live OS at the next reboot).

Then we execute `spma-run --get-be-name` to get the name of the BE that the previous invocation of `spma-run` just created for us (it just extracts that from the `--be-name` argument of the `pkg install` command), so that we can mount up that BE to a mount-point, do a quick security scan of it and touch another special flag file inside it (`configure_on_boot`).

Then the shutdown/reboot process continues and when the host comes back up, it is now booting into the new BE that SPMA created for us, whereupon the `configure_on_boot` flag file we just created tells one of our start scripts to run another `ncm-ncd -configure all`.

This way we have a number of benefits:

   * All components are up-to-date prior to installing any new packages.
   * Packages are only updated on reboot in a new boot environment, not in the live OS.
   * All components are up-to-date after installation of any new packages.
   * We can easily revert to previous state if anything went wrong (by reactivating the old boot environment and rebooting into that).

This is not seriously strange, it is seriously clever :smirk:

**Comment by stdweird** [comment]
:smile: 
but any configuration changes that require a new/updated component, need 2 reboots before they are active?

what is the advantage of having `ncm-ncd --co spma` not doing the actual updates performed by `spma-run` (if you could disable spma component separately)?
and do you perform any other non-spma updates on live OS?

**Comment by stdweird** [comment]
@msmark do you have any objections against removing `spma-run` fron the (linux) rpm?

**Comment by msmark** [comment]
We have other non-SPMA updates to make on the new BE before we want to boot into it.

No objections if you want to remove it from the Linux RPM.

**Comment by stdweird** [comment]
with https://github.com/quattor/configuration-modules-core/issues/768 merged, i'm closing this.
