### ISSUE TITLE
ncm-opennebula : group management not implemented

### ISSUE THREAD

**Issue by StephaneGerardVUB** [quattor/configuration-modules-core#820]
Not possible to create groups or to assign a user to a group

**Comment by alvarosimon** [comment]
Yes, groups are not managed from the component at this moment. 
Just one question about this, do you want to manage and synchronize your regular cloud users from quattor component as well?
 
I'm asking because in our case to sync VSC users we are using an external script to connect to the accounting api to gather the active users and then synchronize the opennebula accounts and VOs through the opennebula RPC endpoint. But in any case we can manage special groups from the component as well, for these groups we will include the flag `QUATTOR="1"` just to know that is managed by quattor itself.

**Comment by StephaneGerardVUB** [comment]
I would like to integrate our cloud in EGI FedCloud, and the rocci part described here :
https://wiki.egi.eu/wiki/rOCCI:ROCCI-server_Admin_Guide
requires some group management tasks.

I'm also interested in giving direct access to vsc users, I'm able to retrieve the vsc accounts using the python tools that are available in Ghent's Github. But I have not yet decided how to "inject" these accounts in OpenNebula.

**Comment by alvarosimon** [comment]
ah ok, I see. You need to generate the groups to assign `rocci` user to `oneadmin` group and also to create a group for each EGI VO. EGI fedcloud users are management by perun I guess.. so that's no handled by quattor. That should be easy to implement, I want to finish the ONE 5.0 support first (I hope to do that during this/next week).

About the VSC users we wrote a script to do that, ONEconnector script from UGentHPC private github. Basically what it does is to query vsc accounting page to gather the users,groups and ssh keys and then update the OpenNebula database through the RPC endpoint. We wrote the script in perl to re-use ` perl-Net-OpenNebula` methods, in the same way as we did with the quattor aii. This is a testing script, not in production yet...
