### ISSUE TITLE
ncm-opennebula: src/test/perl/host.t fails with Net::OpenNebula 0.309.0

### ISSUE THREAD

**Issue by jrha** [quattor/configuration-modules-core#966]
I've been trying to figure out why this is happening now when it didn't happen for RC1.
Perhaps I've managed to mess up my build environment again, but as always I start with a clean VM each time.

The verbose log for the relevant test is [in this gist](https://gist.github.com/jrha/102fb31d6f8fb233fb458bb46069e42a).

Any ideas?

**Comment by alvarosimon** [comment]
Mmm...
rpc history test is failing and probably is because to the SL6 `Net::OpenNebula` rpm, now the rpc api is making less calls than before, maybe that's the issue so the history differs. I didn't check the ncm-opennebula in the last releases, but it is strange that it was working fine in RC1 (any change related with `perl-Net-OpenNebula` version?). 
It's possible to check the host rpc history changing line 28 in `host.t`  to `diag_rpc_history`   to see the previous history, I will take a look.
@stdweird any other ideas?

**Comment by jrha** [comment]
That spits out a single line of:
```
# DEBUG rpc_history one.hostpool.info, one.hostpool.info, one.host.status, one.hostpool.info, one.host.status, one.hostpool.info, one.host.status, one.hostpool.info, one.datastorepool.info, one.host.allocate, one.host.info, one.hostpool.info
```

The other interesting error is:
```
Use of uninitialized value in string eq at /home/tkk76468/quattordev/repos/configuration-modules-core/ncm-opennebula/target/lib/perl/NCM/Component/opennebula.pm line 325.
```

**Comment by jrha** [comment]
I've also updated the gist.

**Comment by alvarosimon** [comment]
the rpc history is wrong, `host.t` is waiting for these methods:

> ok(rpc_history_ok(["one.hostpool.info",
>                    "one.host.enable",
>                    "one.datastorepool.info",
>                    "one.host.allocate",
>                    "one.host.info",
>                    "one.hostpool.info"]),
>                    "manage_something host kvm history ok");

and it seems that `one.host.enable` method is missing in the rpc_history, also in the gist I can't see the datastore template, `TM_MAD = "ceph"`  is not there (probably that's the reason why the history test is failing because it's trying to enable a hyp with ceph and the template is not available), that's strange...

I'm not able to reproduce the issue in my laptop with maven, I have to deploy a SL6 VM and try... do you have the same issue in SL7?

**Comment by jrha** [comment]
After a bit of digging it seems that RC1 was built with Net-OpenNebula-0.308.0, but build_all_repos is installing Net-OpenNebula-0.309.0 which was appeared yesterday (bad timing). I will switch back to 0.308.0 and see what happens.

**Comment by jrha** [comment]
All tests do indeed pass with Net-OpenNebula-0.308.0!
So I conclude that the current component is not compatible with the newer version.

**Comment by alvarosimon** [comment]
👍 perfect, but it's a bit strange the package was updated to fix an issue to enable the hosts in ONE 5.x, nothing else...I have to take a look, I'm writing an new PR to use the new Net-OpenNebula version

**Comment by jrha** [comment]
I've updated this to reflect the underlying issue and left it open for later investigation, thanks for your help.

**Comment by stdweird** [comment]
@alvarosimon with new net -opennebula, it might try new `status` rpc call?

**Comment by alvarosimon** [comment]
@stdweird probably yes, ncm-opennebula is not using `status` call directly only enables or disables the hypervisors if something is wrong. After ONE 5.x they have included a new node status called `offline`  (the hyp is not longer monitored by OpenNebula), that is not the same than `disabled` (the hyp is not used to deploy VMs but it is still monitored). I have to test this a bit more with, `Net::OpenNebula` 0.309.0 maybe there are some side effects that I didn't take into account...

**Comment by alvarosimon** [comment]
Ok I'm able to reproduce the issue,  I was using `0.308.0` instead `0.309.0` , my fault 😭 , I will fix this asap
